In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv('cars.csv')
df.head()

symboling normalized-losses         make fuel-type   body-style  \
0          3                 ?  alfa-romero       gas  convertible   
1          3                 ?  alfa-romero       gas  convertible   
2          1                 ?  alfa-romero       gas    hatchback   
3          2               164         audi       gas        sedan   
4          2               164         audi       gas        sedan   

  drive-wheels engine-location  width  height engine-type  engine-size  \
0          rwd           front   64.1    48.8        dohc          130   
1          rwd           front   64.1    48.8        dohc          130   
2          rwd           front   65.5    52.4        ohcv          152   
3          fwd           front   66.2    54.3         ohc          109   
4          4wd           front   66.4    54.3         ohc          136   

  horsepower  city-mpg  highway-mpg  price  
0        111        21           27  13495  
1        111        21           27  16500  
2        154        19           26  16500  
3        102        24           30  13950  
4        115        18           22  17450

In [3]:
df.replace('?', np.nan, inplace=True)

In [4]:
from sklearn.impute import SimpleImputer

In [5]:
si = SimpleImputer()

In [6]:
df.iloc[:,[1,11]] = si.fit_transform(df.iloc[:,[1,11]])
df.head()

symboling  normalized-losses         make fuel-type   body-style  \
0          3              122.0  alfa-romero       gas  convertible   
1          3              122.0  alfa-romero       gas  convertible   
2          1              122.0  alfa-romero       gas    hatchback   
3          2              164.0         audi       gas        sedan   
4          2              164.0         audi       gas        sedan   

  drive-wheels engine-location  width  height engine-type  engine-size  \
0          rwd           front   64.1    48.8        dohc          130   
1          rwd           front   64.1    48.8        dohc          130   
2          rwd           front   65.5    52.4        ohcv          152   
3          fwd           front   66.2    54.3         ohc          109   
4          4wd           front   66.4    54.3         ohc          136   

   horsepower  city-mpg  highway-mpg  price  
0       111.0        21           27  13495  
1       111.0        21           27  16500  
2       154.0        19           26  16500  
3       102.0        24           30  13950  
4       115.0        18           22  17450

In [7]:
from sklearn.preprocessing import OrdinalEncoder

In [8]:
catcols = df.select_dtypes(object).columns

In [10]:
oe = OrdinalEncoder()

In [12]:
df[catcols] = oe.fit_transform(df[catcols])

In [13]:
df.head()

symboling  normalized-losses  make  fuel-type  body-style  drive-wheels  \
0          3              122.0   0.0        1.0         0.0           2.0   
1          3              122.0   0.0        1.0         0.0           2.0   
2          1              122.0   0.0        1.0         2.0           2.0   
3          2              164.0   1.0        1.0         3.0           1.0   
4          2              164.0   1.0        1.0         3.0           0.0   

   engine-location  width  height  engine-type  engine-size  horsepower  \
0              0.0   64.1    48.8          0.0          130       111.0   
1              0.0   64.1    48.8          0.0          130       111.0   
2              0.0   65.5    52.4          5.0          152       154.0   
3              0.0   66.2    54.3          3.0          109       102.0   
4              0.0   66.4    54.3          3.0          136       115.0   

   city-mpg  highway-mpg  price  
0        21           27  13495  
1        21           27  16500  
2        19           26  16500  
3        24           30  13950  
4        18           22  17450

In [14]:
x = df.drop(columns=['price'])
y = df['price']

In [17]:
from sklearn.model_selection import train_test_split

In [37]:
xtrain,xtest,ytrain,ytest = train_test_split(x,y, test_size=0.3,random_state=1)

In [38]:
xtrain

symboling  normalized-losses  make  fuel-type  body-style  drive-wheels  \
124          3              122.0  14.0        1.0         2.0           2.0   
181         -1              122.0  19.0        1.0         4.0           2.0   
154          0               81.0  19.0        1.0         4.0           0.0   
53           1              113.0   8.0        1.0         3.0           1.0   
94           1              128.0  12.0        1.0         3.0           1.0   
..         ...                ...   ...        ...         ...           ...   
133          2              104.0  17.0        1.0         3.0           1.0   
137          2              104.0  17.0        1.0         3.0           1.0   
72           3              142.0   9.0        1.0         0.0           2.0   
140          2               83.0  18.0        1.0         2.0           0.0   
37           0              106.0   5.0        1.0         2.0           1.0   

     engine-location  width  height  engine-type  engine-size  horsepower  \
124              0.0   66.3    50.2          3.0          156       145.0   
181              0.0   66.5    54.1          0.0          161       156.0   
154              0.0   63.6    59.1          3.0           92        62.0   
53               0.0   64.2    54.1          3.0           91        68.0   
94               0.0   63.8    54.5          3.0           97        69.0   
..               ...    ...     ...          ...          ...         ...   
133              0.0   66.5    56.1          3.0          121       110.0   
137              0.0   66.5    56.1          0.0          121       160.0   
72               0.0   70.5    50.8          5.0          234       155.0   
140              0.0   63.8    55.7          4.0          108        73.0   
37               0.0   65.2    53.3          3.0          110        86.0   

     city-mpg  highway-mpg  
124        19           24  
181        19           24  
154        27           32  
53         31           38  
94         31           37  
..        ...          ...  
133        21           28  
137        19           26  
72         16           18  
140        26           31  
37         27           33  

[143 rows x 14 columns]

In [39]:
from sklearn.linear_model import LinearRegression

In [40]:
lr = LinearRegression()

model = lr.fit(xtrain,ytrain)
pred = model.predict(xtest)

train = model.score(xtrain,ytrain)
test = model.score(xtest,ytest)

print(f"Train accuracy {train}\nTest accuracy {test}")

Train accuracy 0.8504573774895472
Test accuracy 0.7965566780397382


In [41]:
model.coef_

array([ 4.51384957e+01,  1.53127607e+00, -2.00099087e+02, -6.22650015e+02,
       -1.70235175e+02,  1.86860719e+03,  1.64133620e+04,  7.89452171e+02,
        3.62663990e+02,  2.83174279e+02,  9.83682875e+01, -1.08169245e+01,
        3.08017854e+02, -4.17024371e+02])

In [42]:
from sklearn.linear_model import Ridge, Lasso

# Ridge

In [43]:
rg = Ridge(alpha=10)

In [45]:
model = rg.fit(xtrain,ytrain)
rpred = model.predict(xtest)

In [46]:
train = model.score(xtrain,ytrain)
test = model.score(xtest,ytest)

print(f"Train accuracy {train}\nTest accuracy {test}")

Train accuracy 0.8109538582620315
Test accuracy 0.8150222867376525


In [47]:
model.coef_

array([ 2.08658930e+02, -5.60173023e-01, -1.86340249e+02, -9.06610516e+02,
       -6.30655861e+02,  1.56860422e+03,  2.57047785e+03,  3.64420144e+02,
        5.72916414e+02,  5.15948757e+02,  1.04441215e+02,  2.21332730e+01,
        2.11271281e+02, -2.72864381e+02])

# Lasso

In [49]:
ls = Lasso(alpha=10)

model = ls.fit(xtrain,ytrain)
lspred = model.predict(xtest)

In [51]:
train = model.score(xtrain,ytrain)
test = model.score(xtest,ytest)

print(f"Train accuracy {train}\nTest accuracy {test}")

Train accuracy 0.8503221004773043
Test accuracy 0.7982450097819798


# Hyperparameter tuning

In [54]:
for i in range(150,200):
    ls = Lasso(alpha=i)
    ls.fit(xtrain,ytrain)
    train = ls.score(xtrain,ytrain)
    test = ls.score(xtest,ytest)
    
    print(f"{i} {train} {test}")

150 0.8212288879856346 0.8124969899539802
151 0.8208421468238059 0.8125456274822552
152 0.8204526518423789 0.8125934728624999
153 0.8200607762157638 0.8126404383406128
154 0.8196661304388357 0.812686613158391
155 0.8192691148773522 0.8127319078642978
156 0.8188695301369726 0.8127763675886548
157 0.8184671715223708 0.8128200339758357
158 0.818062449862035 0.8128628223230777
159 0.8176549464501084 0.8129048166168777
160 0.8172450881050914 0.8129459336049878
161 0.8168324400154192 0.8129862557319262
162 0.8164174452457785 0.8130257013815374
163 0.8159998820785823 0.8130643120104756
164 0.8155795285150103 0.8131021244780069
165 0.8151568303042497 0.8131390636923393
166 0.8147313271293923 0.8131752048184053
167 0.8143034914835354 0.8132104730535141
168 0.8138728445987574 0.8132449418027805
169 0.8134398734696936 0.8132785388258218
170 0.8130040832573873 0.8133113351310719
171 0.8125659771958964 0.8133432609587987
172 0.8121250442517013 0.8133743847411005
173 0.8116818034536712 0.81340463945

In [56]:
ls = Lasso(alpha=170)

model = ls.fit(xtrain,ytrain)

pred = model.predict(xtest)

In [57]:
train = model.score(xtrain,ytrain)
test = model.score(xtest,ytest)

print(f"Train accuracy {train}\nTest accuracy {test}")

Train accuracy 0.8130040832573873
Test accuracy 0.8133113351310719


In [58]:
model.coef_

array([ 4.43490130e+00,  2.00056602e+00, -1.72066327e+02, -0.00000000e+00,
       -3.70073745e+02,  1.23453446e+03,  4.27843994e+03,  3.99653319e+02,
        4.53832760e+02,  3.01208227e+02,  1.13098477e+02,  1.02575283e+01,
        8.04028285e+01, -1.69892755e+02])